/**
 * Claude Spec File Generator
 *
 * Produces a .claude spec file combining:
 * - Shapie shape data (name, problem, participants, slack channel)
 * - Wolfie session config (prompts, search settings, LLM settings)
 * - Wolfie UI customizations (CSS variable overrides + custom CSS rules)
 * - Shaping session transcript
 *
 * The output is a structured markdown spec that Claude can consume
 * as a project brief / implementation spec.
 */

import { DEFAULT_WOLFIE_PROMPTS } from './wolfieConfig';

/**
 * Generate a complete Claude spec from shape + wolfie + session data.
 *
 * @param {object} params
 * @param {object} params.shape - Shapie shape object
 * @param {object|null} params.wolfieConfig - Wolfie config (prompts, search, llm)
 * @param {Array} params.messages - Shaping session messages
 * @returns {string} The full .claude spec content
 */
export function generateClaudeSpec({ shape, wolfieConfig, messages }) {
  const lines = [];

  // ---- Header ----
  lines.push(`# ${shape.name || 'Untitled Shape'}`);
  lines.push('');
  lines.push(`> Generated by Shapie on ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  // ---- Shape Overview ----
  lines.push('## Shape Overview');
  lines.push('');
  lines.push(`**Name:** ${shape.name || 'Untitled'}`);
  lines.push(`**Status:** ${shape.status || 'raw_idea'}`);
  if (shape.appetite) {
    lines.push(`**Appetite:** ${shape.appetite === 'big_batch' ? 'Big Batch (6 weeks)' : 'Small Batch (1-2 weeks)'}`);
  }
  lines.push('');

  // ---- Problem ----
  lines.push('## Problem');
  lines.push('');
  lines.push(shape.problem || '_No problem statement defined._');
  lines.push('');

  // ---- Participants ----
  const participants = shape.participants || [];
  if (participants.length > 0) {
    lines.push('## Participants');
    lines.push('');
    lines.push('| Name | Role | Title |');
    lines.push('|------|------|-------|');
    for (const p of participants) {
      const role = p.role || '—';
      const title = p.title || '—';
      lines.push(`| ${p.name} | ${role} | ${title} |`);
    }
    lines.push('');
  }

  // ---- Slack Channel ----
  if (shape.slackChannel) {
    lines.push('## Slack Channel');
    lines.push('');
    lines.push(`**Channel:** #${shape.slackChannel.name}`);
    if (shape.slackChannel.channelId) {
      lines.push(`**Channel ID:** ${shape.slackChannel.channelId}`);
    }
    lines.push('');
  }

  // ---- Wolfie Configuration ----
  lines.push('## Wolfie Configuration');
  lines.push('');

  if (wolfieConfig) {
    // Search settings
    lines.push('### Search Settings');
    lines.push('');
    const searchProvider = wolfieConfig.searchProvider || 'cimulate';
    const searchCatalog = wolfieConfig.searchCatalog || wolfieConfig.catalog || '';
    lines.push(`- **Provider:** ${searchProvider}`);
    if (searchCatalog) {
      lines.push(`- **Catalog:** ${searchCatalog}`);
    }
    if (wolfieConfig.maxResults) {
      lines.push(`- **Max Results:** ${wolfieConfig.maxResults}`);
    }
    lines.push('');

    // LLM settings
    lines.push('### LLM Settings');
    lines.push('');
    lines.push(`- **Model:** ${wolfieConfig.llmModel || 'gpt-4o-mini'}`);
    lines.push(`- **API URL:** ${wolfieConfig.llmApiUrl || 'SF AI Model Gateway (default)'}`);
    lines.push('');

    // Prompts
    lines.push('### Prompts');
    lines.push('');

    const prompts = wolfieConfig.prompts || {};
    const promptEntries = [
      { key: 'explanation', label: 'Explanation Prompt' },
      { key: 'bestPick', label: 'Best Pick Prompt' },
      { key: 'reformulations', label: 'Reformulations Prompt' },
    ];

    for (const { key, label } of promptEntries) {
      const template = prompts[key] || DEFAULT_WOLFIE_PROMPTS[key] || '';
      const isCustom = prompts[key] && prompts[key] !== DEFAULT_WOLFIE_PROMPTS[key];
      lines.push(`#### ${label}${isCustom ? ' (customized)' : ' (default)'}`);
      lines.push('');
      lines.push('```');
      lines.push(template);
      lines.push('```');
      lines.push('');
    }

    // UI Customizations
    const uiCustomizations = wolfieConfig.uiCustomizations || {};
    const uiCustomCSS = wolfieConfig.uiCustomCSS || '';
    const hasVarOverrides = Object.keys(uiCustomizations).length > 0;
    const hasCSSRules = uiCustomCSS.trim().length > 0;

    if (hasVarOverrides || hasCSSRules) {
      lines.push('### UI Customizations');
      lines.push('');
      lines.push('_The following UI changes were applied via the "Change UI" chat in Wolfie._');
      lines.push('');

      if (hasVarOverrides) {
        lines.push('#### CSS Variable Overrides');
        lines.push('');
        lines.push('| Variable | Value |');
        lines.push('|----------|-------|');
        for (const [varName, value] of Object.entries(uiCustomizations)) {
          lines.push(`| \`${varName}\` | \`${value}\` |`);
        }
        lines.push('');
      }

      if (hasCSSRules) {
        lines.push('#### Custom CSS Rules');
        lines.push('');
        lines.push('```css');
        lines.push(uiCustomCSS.trim());
        lines.push('```');
        lines.push('');
      }
    }
  } else {
    lines.push('_Wolfie configuration not available. Using defaults._');
    lines.push('');
  }

  // ---- Solution (if any from shape editor) ----
  const solution = shape.solution || {};
  if (solution.sketch || solution.boundaries || solution.rabbitHoles || solution.noGos) {
    lines.push('## Solution');
    lines.push('');
    if (solution.sketch) {
      lines.push('### Sketch');
      lines.push('');
      lines.push(solution.sketch);
      lines.push('');
    }
    if (solution.boundaries) {
      lines.push('### Boundaries');
      lines.push('');
      lines.push(solution.boundaries);
      lines.push('');
    }
    if (solution.rabbitHoles) {
      lines.push('### Rabbit Holes');
      lines.push('');
      lines.push(solution.rabbitHoles);
      lines.push('');
    }
    if (solution.noGos) {
      lines.push('### No-Gos');
      lines.push('');
      lines.push(solution.noGos);
      lines.push('');
    }
  }

  // ---- Scope ----
  const scope = shape.scope || [];
  if (scope.length > 0) {
    lines.push('## Scope');
    lines.push('');
    for (const item of scope) {
      const check = item.done ? 'x' : ' ';
      lines.push(`- [${check}] ${item.title || '(untitled)'}`);
    }
    lines.push('');
  }

  // ---- Shaping Session Transcript ----
  if (messages && messages.length > 0) {
    lines.push('## Shaping Session');
    lines.push('');
    lines.push('### Transcript');
    lines.push('');
    lines.push('<details>');
    lines.push('<summary>Full session transcript</summary>');
    lines.push('');
    for (const msg of messages) {
      const role = msg.role === 'user' ? '**Shaper**' : '**Shapie**';
      lines.push(`${role}: ${msg.content}`);
      lines.push('');
    }
    lines.push('</details>');
    lines.push('');

    // Extract key decisions / insights from assistant messages
    const assistantMsgs = messages.filter((m) => m.role === 'assistant' && !m.isError);
    if (assistantMsgs.length > 0) {
      lines.push('### Key Insights');
      lines.push('');
      lines.push('_Extracted from the shaping session:_');
      lines.push('');
      // Take the last few assistant messages as the most refined insights
      const recent = assistantMsgs.slice(-3);
      for (const msg of recent) {
        const preview = msg.content.length > 300
          ? msg.content.slice(0, 300) + '...'
          : msg.content;
        lines.push(`> ${preview.replace(/\n/g, '\n> ')}`);
        lines.push('');
      }
    }
  }

  // ---- Changes from Defaults ----
  if (wolfieConfig) {
    const changes = collectChangesFromDefaults(wolfieConfig);
    if (changes.length > 0) {
      lines.push('## Changes from Defaults');
      lines.push('');
      lines.push('_Summary of all Wolfie configuration changes relative to out-of-the-box defaults._');
      lines.push('');
      for (const change of changes) {
        lines.push(`- **${change.category}** — ${change.description}`);
      }
      lines.push('');
    }
  }

  // ---- Footer ----
  lines.push('---');
  lines.push('');
  lines.push(`_Spec generated by Shapie | Shape: ${shape.name || 'Untitled'} | ${new Date().toLocaleString()}_`);

  return lines.join('\n');
}

/**
 * Generate the spec and trigger a file download.
 *
 * @param {object} params - Same as generateClaudeSpec
 * @param {string} [filename] - Override filename
 */
export function downloadClaudeSpec(params, filename) {
  const content = generateClaudeSpec(params);
  const name = filename || `${slugify(params.shape.name || 'untitled')}.claude.md`;

  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return content;
}

/**
 * Default Wolfie configuration values.
 * Used to detect what the user changed from out-of-the-box settings.
 */
const WOLFIE_DEFAULTS = {
  searchProvider: 'cimulate',
  searchCatalog: 'cephora',
  maxResults: 8,
  llmModel: 'gpt-4o-mini',
  llmApiUrl: null,
};

/**
 * Collect a list of human-readable changes from default Wolfie configuration.
 *
 * @param {object} wolfieConfig
 * @returns {Array<{category: string, description: string}>}
 */
function collectChangesFromDefaults(wolfieConfig) {
  const changes = [];

  // Search settings
  const provider = wolfieConfig.searchProvider || WOLFIE_DEFAULTS.searchProvider;
  if (provider !== WOLFIE_DEFAULTS.searchProvider) {
    changes.push({
      category: 'Search Provider',
      description: `Changed from \`${WOLFIE_DEFAULTS.searchProvider}\` to \`${provider}\``,
    });
  }

  const catalog = wolfieConfig.searchCatalog || wolfieConfig.catalog || WOLFIE_DEFAULTS.searchCatalog;
  if (catalog !== WOLFIE_DEFAULTS.searchCatalog) {
    changes.push({
      category: 'Search Catalog',
      description: `Changed from \`${WOLFIE_DEFAULTS.searchCatalog}\` to \`${catalog}\``,
    });
  }

  const maxResults = wolfieConfig.maxResults || WOLFIE_DEFAULTS.maxResults;
  if (maxResults !== WOLFIE_DEFAULTS.maxResults) {
    changes.push({
      category: 'Max Results',
      description: `Changed from \`${WOLFIE_DEFAULTS.maxResults}\` to \`${maxResults}\``,
    });
  }

  // LLM settings
  const model = wolfieConfig.llmModel || WOLFIE_DEFAULTS.llmModel;
  if (model !== WOLFIE_DEFAULTS.llmModel) {
    changes.push({
      category: 'LLM Model',
      description: `Changed from \`${WOLFIE_DEFAULTS.llmModel}\` to \`${model}\``,
    });
  }

  if (wolfieConfig.llmApiUrl && wolfieConfig.llmApiUrl !== WOLFIE_DEFAULTS.llmApiUrl) {
    changes.push({
      category: 'LLM API URL',
      description: `Custom endpoint: \`${wolfieConfig.llmApiUrl}\``,
    });
  }

  // Prompt customizations
  const prompts = wolfieConfig.prompts || {};
  const promptLabels = {
    explanation: 'Explanation Prompt',
    bestPick: 'Best Pick Prompt',
    reformulations: 'Reformulations Prompt',
  };

  for (const [key, label] of Object.entries(promptLabels)) {
    if (prompts[key] && prompts[key] !== DEFAULT_WOLFIE_PROMPTS[key]) {
      // Show a short preview of what changed
      const preview = prompts[key].length > 80
        ? prompts[key].slice(0, 80).replace(/\n/g, ' ') + '...'
        : prompts[key].replace(/\n/g, ' ');
      changes.push({
        category: label,
        description: `Customized (starts with: "${preview}")`,
      });
    }
  }

  // UI Customizations — CSS variable overrides
  const uiCustomizations = wolfieConfig.uiCustomizations || {};
  const varOverrideCount = Object.keys(uiCustomizations).length;
  if (varOverrideCount > 0) {
    const varNames = Object.keys(uiCustomizations).map((v) => `\`${v}\``).join(', ');
    changes.push({
      category: 'UI Variables',
      description: `${varOverrideCount} CSS variable${varOverrideCount > 1 ? 's' : ''} overridden: ${varNames}`,
    });
  }

  // UI Customizations — custom CSS rules
  const uiCustomCSS = (wolfieConfig.uiCustomCSS || '').trim();
  if (uiCustomCSS.length > 0) {
    // Count the number of rule blocks
    const ruleCount = (uiCustomCSS.match(/\{/g) || []).length;
    changes.push({
      category: 'UI Custom CSS',
      description: `${ruleCount} custom CSS rule${ruleCount !== 1 ? 's' : ''} injected`,
    });
  }

  return changes;
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60);
}
