/**
 * Claude Spec File Generator
 *
 * Produces a .claude spec file combining:
 * - Shapie shape data (name, problem, participants, slack channel)
 * - Wolfie session config (prompts, search settings, LLM settings)
 * - Shaping session transcript
 *
 * The output is a structured markdown spec that Claude can consume
 * as a project brief / implementation spec.
 */

import { DEFAULT_WOLFIE_PROMPTS } from './wolfieConfig';

/**
 * Generate a complete Claude spec from shape + wolfie + session data.
 *
 * @param {object} params
 * @param {object} params.shape - Shapie shape object
 * @param {object|null} params.wolfieConfig - Wolfie config (prompts, search, llm)
 * @param {Array} params.messages - Shaping session messages
 * @returns {string} The full .claude spec content
 */
export function generateClaudeSpec({ shape, wolfieConfig, messages }) {
  const lines = [];

  // ---- Header ----
  lines.push(`# ${shape.name || 'Untitled Shape'}`);
  lines.push('');
  lines.push(`> Generated by Shapie on ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  // ---- Shape Overview ----
  lines.push('## Shape Overview');
  lines.push('');
  lines.push(`**Name:** ${shape.name || 'Untitled'}`);
  lines.push(`**Status:** ${shape.status || 'raw_idea'}`);
  if (shape.appetite) {
    lines.push(`**Appetite:** ${shape.appetite === 'big_batch' ? 'Big Batch (6 weeks)' : 'Small Batch (1-2 weeks)'}`);
  }
  lines.push('');

  // ---- Problem ----
  lines.push('## Problem');
  lines.push('');
  lines.push(shape.problem || '_No problem statement defined._');
  lines.push('');

  // ---- Participants ----
  const participants = shape.participants || [];
  if (participants.length > 0) {
    lines.push('## Participants');
    lines.push('');
    lines.push('| Name | Role | Title |');
    lines.push('|------|------|-------|');
    for (const p of participants) {
      const role = p.role || '—';
      const title = p.title || '—';
      lines.push(`| ${p.name} | ${role} | ${title} |`);
    }
    lines.push('');
  }

  // ---- Slack Channel ----
  if (shape.slackChannel) {
    lines.push('## Slack Channel');
    lines.push('');
    lines.push(`**Channel:** #${shape.slackChannel.name}`);
    if (shape.slackChannel.channelId) {
      lines.push(`**Channel ID:** ${shape.slackChannel.channelId}`);
    }
    lines.push('');
  }

  // ---- Wolfie Configuration ----
  lines.push('## Wolfie Configuration');
  lines.push('');

  if (wolfieConfig) {
    // Search settings
    lines.push('### Search Settings');
    lines.push('');
    lines.push(`- **Provider:** ${wolfieConfig.searchProvider || 'cimulate'}`);
    if (wolfieConfig.catalog) {
      lines.push(`- **Catalog:** ${wolfieConfig.catalog}`);
    }
    lines.push('');

    // LLM settings
    lines.push('### LLM Settings');
    lines.push('');
    lines.push(`- **Model:** ${wolfieConfig.llmModel || 'gpt-4o-mini'}`);
    lines.push(`- **API URL:** ${wolfieConfig.llmApiUrl || 'SF AI Model Gateway (default)'}`);
    lines.push('');

    // Prompts
    lines.push('### Prompts');
    lines.push('');

    const prompts = wolfieConfig.prompts || {};
    const promptEntries = [
      { key: 'explanation', label: 'Explanation Prompt' },
      { key: 'bestPick', label: 'Best Pick Prompt' },
      { key: 'reformulations', label: 'Reformulations Prompt' },
    ];

    for (const { key, label } of promptEntries) {
      const template = prompts[key] || DEFAULT_WOLFIE_PROMPTS[key] || '';
      const isCustom = prompts[key] && prompts[key] !== DEFAULT_WOLFIE_PROMPTS[key];
      lines.push(`#### ${label}${isCustom ? ' (customized)' : ' (default)'}`);
      lines.push('');
      lines.push('```');
      lines.push(template);
      lines.push('```');
      lines.push('');
    }
  } else {
    lines.push('_Wolfie configuration not available. Using defaults._');
    lines.push('');
  }

  // ---- Solution (if any from shape editor) ----
  const solution = shape.solution || {};
  if (solution.sketch || solution.boundaries || solution.rabbitHoles || solution.noGos) {
    lines.push('## Solution');
    lines.push('');
    if (solution.sketch) {
      lines.push('### Sketch');
      lines.push('');
      lines.push(solution.sketch);
      lines.push('');
    }
    if (solution.boundaries) {
      lines.push('### Boundaries');
      lines.push('');
      lines.push(solution.boundaries);
      lines.push('');
    }
    if (solution.rabbitHoles) {
      lines.push('### Rabbit Holes');
      lines.push('');
      lines.push(solution.rabbitHoles);
      lines.push('');
    }
    if (solution.noGos) {
      lines.push('### No-Gos');
      lines.push('');
      lines.push(solution.noGos);
      lines.push('');
    }
  }

  // ---- Scope ----
  const scope = shape.scope || [];
  if (scope.length > 0) {
    lines.push('## Scope');
    lines.push('');
    for (const item of scope) {
      const check = item.done ? 'x' : ' ';
      lines.push(`- [${check}] ${item.title || '(untitled)'}`);
    }
    lines.push('');
  }

  // ---- Shaping Session Transcript ----
  if (messages && messages.length > 0) {
    lines.push('## Shaping Session');
    lines.push('');
    lines.push('### Transcript');
    lines.push('');
    lines.push('<details>');
    lines.push('<summary>Full session transcript</summary>');
    lines.push('');
    for (const msg of messages) {
      const role = msg.role === 'user' ? '**Shaper**' : '**Shapie**';
      lines.push(`${role}: ${msg.content}`);
      lines.push('');
    }
    lines.push('</details>');
    lines.push('');

    // Extract key decisions / insights from assistant messages
    const assistantMsgs = messages.filter((m) => m.role === 'assistant' && !m.isError);
    if (assistantMsgs.length > 0) {
      lines.push('### Key Insights');
      lines.push('');
      lines.push('_Extracted from the shaping session:_');
      lines.push('');
      // Take the last few assistant messages as the most refined insights
      const recent = assistantMsgs.slice(-3);
      for (const msg of recent) {
        const preview = msg.content.length > 300
          ? msg.content.slice(0, 300) + '...'
          : msg.content;
        lines.push(`> ${preview.replace(/\n/g, '\n> ')}`);
        lines.push('');
      }
    }
  }

  // ---- Footer ----
  lines.push('---');
  lines.push('');
  lines.push(`_Spec generated by Shapie | Shape: ${shape.name || 'Untitled'} | ${new Date().toLocaleString()}_`);

  return lines.join('\n');
}

/**
 * Generate the spec and trigger a file download.
 *
 * @param {object} params - Same as generateClaudeSpec
 * @param {string} [filename] - Override filename
 */
export function downloadClaudeSpec(params, filename) {
  const content = generateClaudeSpec(params);
  const name = filename || `${slugify(params.shape.name || 'untitled')}.claude.md`;

  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return content;
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60);
}
